### ISSUE TITLE
Build failure after dc1d7bd24796272f5b1a852be2055f8c0b1d819c  (avfilter/vf_neighbor: add frame threading)

### ISSUE THREAD

**Issue by rorgoroth** [librempeg/librempeg#50]
https://github.com/librempeg/librempeg/commit/dc1d7bd24796272f5b1a852be2055f8c0b1d819c

This recent commit causes a build failure:
```llvm
src/libavfilter/vf_neighbor.c:406:1: error: use of undeclared identifier 'transfer_state'
  406 | DEFINE_NEIGHBOR_FILTER(erosion, "Apply erosion effect.", erosion_dilation, CONFIG_AVFILTER_THREAD_FRAME);
      | ^
src/libavfilter/vf_neighbor.c:381:40: note: expanded from macro 'DEFINE_NEIGHBOR_FILTER'
  381 |     .transfer_state = config_thread_ ? transfer_state : NULL,\
      |                                        ^
src/libavfilter/vf_neighbor.c:412:1: error: use of undeclared identifier 'transfer_state'
  412 | DEFINE_NEIGHBOR_FILTER(dilation, "Apply dilation effect.", erosion_dilation, CONFIG_AVFILTER_THREAD_FRAME);
      | ^
src/libavfilter/vf_neighbor.c:381:40: note: expanded from macro 'DEFINE_NEIGHBOR_FILTER'
  381 |     .transfer_state = config_thread_ ? transfer_state : NULL,\
      |                                        ^
src/libavfilter/vf_neighbor.c:421:1: error: use of undeclared identifier 'transfer_state'
  421 | DEFINE_NEIGHBOR_FILTER(deflate, "Apply deflate effect.", deflate_inflate, CONFIG_AVFILTER_THREAD_FRAME);
      | ^
src/libavfilter/vf_neighbor.c:381:40: note: expanded from macro 'DEFINE_NEIGHBOR_FILTER'
  381 |     .transfer_state = config_thread_ ? transfer_state : NULL,\
      |                                        ^
src/libavfilter/vf_neighbor.c:427:1: error: use of undeclared identifier 'transfer_state'
  427 | DEFINE_NEIGHBOR_FILTER(inflate, "Apply inflate effect.", deflate_inflate, CONFIG_AVFILTER_THREAD_FRAME);
      | ^
src/libavfilter/vf_neighbor.c:381:40: note: expanded from macro 'DEFINE_NEIGHBOR_FILTER'
  381 |     .transfer_state = config_thread_ ? transfer_state : NULL,\
      |                                        ^
4 errors generated.
make: *** [src/ffbuild/common.mak:81: libavfilter/vf_neighbor.o] Error 1
```

Thanks for any help/fixes 👍

**Comment by richardpl** [comment]
you need to add --enable-agpl to configure to build ffmpeg.exe tool now.
