### ISSUE TITLE
Build error caused by 46c991d590933a488c704241de0149d7940ec232 (amfenc: B-Frame support for av1_amf encoder.)

### ISSUE THREAD

**Issue by rorgoroth** [librempeg/librempeg#26]
Building mingw64 with latest llvm release, the build fails since 46c991d590933a488c704241de0149d7940ec232, reverting that commit allows build to complete.

Here is the full build log: 
[ffmpeg.log](https://github.com/user-attachments/files/18219114/ffmpeg.log)

Relevant errors:
```llvm
3378:src/libavcodec/amfenc_av1.c:467:57: error: use of undeclared identifier 'AMF_VIDEO_ENCODER_AV1_ADAPTIVE_MINIGOP'; did you mean 'AMF_VIDEO_ENCODER_AV1_PROFILE_MAIN'?
3379-  467 |             AMF_ASSIGN_PROPERTY_BOOL(res, ctx->encoder, AMF_VIDEO_ENCODER_AV1_ADAPTIVE_MINIGOP, ((ctx->pa_adaptive_mini_gop == 0) ? false : true));
--
3396:src/libavcodec/amfenc_av1.c:482:58: error: use of undeclared identifier 'AMF_VIDEO_ENCODER_AV1_ADAPTIVE_MINIGOP'; did you mean 'AMF_VIDEO_ENCODER_AV1_PROFILE_MAIN'?
3397-  482 |     res = ctx->encoder->pVtbl->GetProperty(ctx->encoder, AMF_VIDEO_ENCODER_AV1_ADAPTIVE_MINIGOP, &is_adaptive_b_frames);
--
3403:src/libavcodec/amfenc_av1.c:490:66: error: use of undeclared identifier 'AMF_VIDEO_ENCODER_AV1_CAP_BFRAMES'
3404-  490 |             res = encoder_caps->pVtbl->GetProperty(encoder_caps, AMF_VIDEO_ENCODER_AV1_CAP_BFRAMES, &var);
--
3406:src/libavcodec/amfenc_av1.c:499:70: error: use of undeclared identifier 'AMF_VIDEO_ENCODER_AV1_MAX_CONSECUTIVE_BPICTURES'
3407-  499 |                         AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_AV1_MAX_CONSECUTIVE_BPICTURES, 3);
--
3409:src/libavcodec/amfenc_av1.c:510:74: error: use of undeclared identifier 'AMF_VIDEO_ENCODER_AV1_B_PIC_PATTERN'; did you mean 'AMF_VIDEO_ENCODER_AV1_PROFILE_MAIN'?
3410-  510 |                             AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_AV1_B_PIC_PATTERN, ctx->max_b_frames);
--
3428:src/libavcodec/amfenc_av1.c:512:86: error: use of undeclared identifier 'AMF_VIDEO_ENCODER_AV1_B_PIC_PATTERN'; did you mean 'AMF_VIDEO_ENCODER_AV1_PROFILE_MAIN'?
3429-  512 |                                 res = ctx->encoder->pVtbl->GetProperty(ctx->encoder, AMF_VIDEO_ENCODER_AV1_B_PIC_PATTERN, &var);
--
3436:src/libavcodec/amfenc_av1.c:516:74: error: use of undeclared identifier 'AMF_VIDEO_ENCODER_AV1_MAX_CONSECUTIVE_BPICTURES'
3437-  516 |                             AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_AV1_MAX_CONSECUTIVE_BPICTURES, ctx->max_b_frames);
--
3451:2 warnings and 7 errors generated.
3452:make: *** [src/ffbuild/common.mak:81: libavcodec/amfenc_av1.o] Error 1
```

Thanks for any help.

**Comment by richardpl** [comment]
If you do not use amfenc just disable relevant module (--disable-amf)
If you do use amfenc, update its headers to newer versions.
If you can not update headers wait for ffmpeg devs to provide proper checks.

**Comment by rorgoroth** [comment]
I feel like an idiot, I saw the amf version bump but already had the latest. I've just been to look to double check I didn't mess up updating amf and it seems they added this *after* the release. Updated to amf git and issue resolved.

Thanks again.
